### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by mewore** [mewore/graphics#36]
Display:
- [x] Sprites
   - [x] Sprite icons
   - [x] Clicking on any sprite leads to ~~image-editor~~ sprite-editor
   - [x] "New sprite" button (#35)
- [x] Tile types
   - [x] Tile type icons
   - [x] Clicking on any tile type leads to ~~image-edtor~~ tile-editor
   - [x] "New tile type" button (#34)
- [x] Maps (WITHOUT thumbnails... at least for now)
   - [x] Clicking on any map leads to map-editor
   - [x] "New map" button (#53)
